# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "My eval"

prompts:
#  - file://prompts/text.txt
  - file://prompts/text-storeOtput.txt
#  - "Write a tweet about {{topic}}"
#  - "Write a concise, funny tweet about {{topic}}"
#  - 'Convert this English to {{language}}: {{input}}'
#  - 'Translate to {{language}}: {{input}}'

providers:
  - id: bedrock:amazon.titan-text-express-v1
    label: titan-text-express-v1
    config:
      region: us-east-1
      maxTokenCount: 8192
      temperature: 0
      topP: 1
      stopSequences: ['END']
#  - id: bedrock:amazon.titan-text-lite-v1
#    label: titan-text-lite-v1
#    config:
#      region: us-east-1
#      maxTokenCount: 4096
#      temperature: 0
#      topP: 1
#      stopSequences: ['END']

# These test properties are applied to every test
#defaultTest:
#  options:
#    provider:
#      text:
#        id: bedrock:amazon.titan-text-express-v1
#        label: titan-text-express-v1
#        config:
#          region: us-east-1
#          maxTokenCount: 8192
#          temperature: 0
#          topP: 1
#          stopSequences: [ 'END' ]
#  assert:
#    # Verify that the output doesn't contain "AI language model"
#    - type: not-contains
#      value: AI language model
#
#    # Verify that the output doesn't apologize
#    - type: llm-rubric
#      value: must not contain an apology
#
#    # Prefer shorter outputs using a scoring function
#    - type: javascript
#      value: Math.max(0, Math.min(1, 1 - (output.length - 100) / 900));

tests:
#  - tests/tests.yaml
  - tests/test-storeOutput-transform.yaml
#  - vars:
#      topic: bananas
#    assert:
#      - type: icontains
#        value: bananas
#  - vars:
#      topic: avocado toast
#    assert:
#      - type: icontains
#        value: bananas
#  - vars:
#      language: French
#      input: Hello world
#    assert:
#      - type: icontains
#        value: Bonjour
#  - vars:
#      language: Spanish
#      input: Where is the library?
#    assert:
#      - type: icontains
#        value: biblioteca


#    assert:
#      # For more information on assertions, see https://promptfoo.dev/docs/configuration/expected-outputs
#
#      # Make sure output contains the word "avocado"
#      - type: icontains
#        value: avocado
#
#      # Prefer shorter outputs
#      - type: javascript
#        value: 1 / (output.length + 1)
#
#  - vars:
#      topic: new york city
#    assert:
#      # For more information on model-graded evals, see https://promptfoo.dev/docs/configuration/expected-outputs/model-graded
#      - type: llm-rubric
#        value: ensure that the output is funny

